#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = ["pillow"]
# ///
# ─── How to run ───
# Install uv: curl -LsSf https://astral.sh/uv/install.sh | sh
# Run: uv run assemble.py
# ──────────────────
"""Deterministically regrid generated art and assemble runtime PNGs."""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Final

from PIL import Image

ROOT: Final = Path(__file__).resolve().parent
GAME: Final = Path('/tmp/subtarune-cats149')
GENERATED: Final = Path('/Users/khope@sionic.ai/.codex/generated_images/01a094db-7a81-76c2-aca4-9bb437fc989a')
SOURCE_NAMES: Final = {
    'bow': 'exec-46512372-71bb-4218-995e-765ed5eb3923.png',
    'axe': 'exec-ffdf3c9c-be3e-48a8-a243-834d9a2038c5.png',
    'burrow': 'exec-4a9c25af-f396-4a50-bd57-ba0265fae2d6.png',
    'glyphs': 'exec-e532475d-e5de-47a8-b5e9-397faf27a3c7.png',
    'mushroom': 'exec-ef3fdd8e-e10b-433e-8e6d-b4283b4b1d1f.png',
    'audience': 'exec-0e7b7314-3083-4d55-9575-3d5bc61df335.png',
    'glyph-jo': 'exec-f57f3453-5477-4536-87be-72468aa58b97.png',
}


def main() -> None:
    """Preserve raw sources, regrid bow without resizing, and export props."""
    for name, filename in SOURCE_NAMES.items():
        folder = ROOT / name
        folder.mkdir(parents=True, exist_ok=True)
        shutil.copy2(GENERATED / filename, folder / 'original-raw.png')
    with Image.open(ROOT / 'bow/original-raw.png') as original:
        bow = Image.new('RGBA', (1254, 1350), (255, 0, 255, 255))
        for row, (top, bottom) in enumerate(((0, 414), (414, 816), (816, 1254))):
            for column in range(2):
                cell = original.crop((column * 627, top, (column + 1) * 627, bottom))
                bow.paste(cell, (column * 627, row * 450))
        bow.save(ROOT / 'bow/regrouped.png')
    with Image.open(ROOT / 'audience/original-raw.png') as original:
        cropped = original.crop((0, 132, 2048, 568)).convert('RGBA')
        reduced = cropped.resize((672, 143), Image.Resampling.NEAREST)
        audience = Image.new('RGBA', (672, 176))
        audience.paste(reduced, (0, 16))
        audience.save(ROOT / 'editor_union_audience.png')
    shutil.copy2(ROOT / 'mushroom/single-1.png', ROOT / 'editor-union-mushroom.png')
    glyphs = Image.new('RGBA', (256, 64))
    for index in range(4):
        source = ROOT / ('glyph-jo/single-1.png' if index == 3 else f'glyphs/single-{index + 1}.png')
        with Image.open(source) as frame:
            bounds = frame.getbbox()
            assert bounds is not None
            letter = frame.crop(bounds)
            glyphs.paste(letter, (index * 64 + (64 - letter.width) // 2, (64 - letter.height) // 2))
    glyphs.save(ROOT / 'editor-union-glyphs.png')
    for asset in ('editor_union_audience.png', 'editor-union-mushroom.png', 'editor-union-glyphs.png'):
        shutil.copy2(ROOT / asset, GAME / 'assets/props' / asset)
    for folder, filename in (('bow/final', 'park-guardian-bow'), ('axe', 'warm-bidet-axe-strike'), ('burrow', 'ttuulla-burrow')):
        shutil.copy2(ROOT / folder / 'sheet-transparent.png', GAME / 'assets/sprites' / f'{filename}.png')
    (ROOT / 'source-contract.json').write_text(json.dumps({
        'generator': 'builtin imagegen, generated by parent agent',
        'original_sources': SOURCE_NAMES,
        'bow_regrid': {'rows': [[0, 414], [414, 816], [816, 1254]], 'cell': [627, 450], 'resized': False},
        'audience': {'crop': [0, 132, 2048, 568], 'resized': [672, 143], 'canvas': [672, 176], 'offset': [0, 16], 'interpolation': 'NEAREST'},
        'raw_art_redrawn': False,
    }, ensure_ascii=False, indent=2) + '\n')


if __name__ == '__main__':
    main()
