// 빛 드는 공터 — 풀숲의 최미스·가순이 셋(BUILD257): QA jjajang_glade_bush 에서 위로 한 걸음 → 트리거 → 1부(흔들림·숨기·최미스 등장·대사·가면 클로즈업·쵸쇼우야·스읍 미스)
//   → 2부(땡떙씨~?·가면 씀·가순이 셋 내려옴·오른쪽 이동·나무 뒤 카메라·가순이 퇴장·얼굴 손·가면 던짐·카메라 아래로·일행 발견·도망·끝). 실행: tests/playtest/run.sh jjajang-glade
import fs from 'node:fs'; import path from 'node:path';
import { chromium } from 'playwright-core';
const shots = process.env.SHOT_DIR; fs.mkdirSync(shots, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXE, headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'warning' && /cutscene|엔티티 없음|동작 없음/.test(m.text())) errors.push('warn: ' + m.text()); });
let fails = 0;
const check = (ok, msg) => { if (!ok) { fails += 1; console.log('FAIL', msg); } else console.log('ok', msg); };
const cap = async n => { await page.screenshot({ path: path.join(shots, 'glade_' + n + '.png') }); };
const press = async key => { await page.keyboard.down(key); await page.waitForTimeout(60); await page.keyboard.up(key); };
const until = (fn, ms) => page.waitForFunction(fn, null, { timeout: ms, polling: 30 }).then(() => true).catch(() => false);
const st = () => page.evaluate(() => { const g = window.game; return { text: g.textbox.node?.text || null, speaker: g.textbox.node?.speaker || null, state: g.textbox.state, cam: [Math.round(g.camera.x), Math.round(g.camera.y)], zoom: +g.zoom.s.toFixed(2), bgm: g.sound.bgmName }; });
const next = async () => { await until(() => window.game.textbox.state === 'waiting', 8000); await press('KeyC'); };
const advanceTo = async (needle, ms = 60000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { const s = await st(); if (s.text && s.text.includes(needle)) return s; if (s.text) await next(); await page.waitForTimeout(100); } return null; };
const ent = id => page.evaluate(i => { const e = window.game.entities.find(x => x.id === i); return e ? { x: Math.round(e.x), y: Math.round(e.y), visible: e.visible !== false, dead: !!e.dead, motion: !!e.motion, facing: e.facing } : null; }, id);
try {
  await page.goto('http://localhost:8000/?qa=jjajang_glade_bush');
  check(await until(() => window.game?.mapId === 'jjajang_glade' && !window.game.transitioning, 30000), '빛 드는 공터 QA 진입');
  const light = await page.evaluate(() => ({ spot: !!window.game.map.def.spotlight, bgm: window.game.sound.bgmName, party: [...window.game.party] }));
  check(light.spot && light.bgm === 'wind' && light.party.join() === 'gyeongsub,ppaman', `빛·브금 wind·동료 둘 ${JSON.stringify(light)}`);
  await cap('00_before');
  await page.keyboard.down('ArrowUp'); check(await until(() => window.game.dialogue.running, 8000), '위로 한 걸음 → 풀숲 연출 시작'); await page.keyboard.up('ArrowUp');
  check(await until(() => (window.game.entities.find(e => e.id === 'glade_bush_2')?.jitter?.t || 0) > 0, 3000), '가운데 풀숲이 흔들린다');
  await page.waitForTimeout(500); await cap('01_rustle');
  check(await until(() => window.game.player.emote?.kind === '!', 4000), '모두 느낌표');
  check(await until(() => window.game.player.facing === 'right', 3000), '오른쪽을 본다');
  let s = await advanceTo('뭐죠'); check(!!s && s.speaker === '억빠맨', '억빠맨: ?? 뭐죠');
  s = await advanceTo('흔..들린'); check(!!s && s.speaker === '경섭', '경섭: 흔..들린거같은데'); await next();
  check(await until(() => window.game.player.x < 13 * 32, 12000), '왼쪽 나무 뒤로 달려가 숨는다');
  await page.waitForTimeout(700); await cap('02_hidden');
  s = await advanceTo('우왁'); check(!!s && s.speaker === '???', '???: 우왁!!!'); await cap('03_uwak'); await next();
  check(await until(() => { const c = window.game.entities.find(e => e.id === 'choimis'); return c && c.visible && (c.hopY || 0) > 5; }, 5000), '최미스가 풀숲에서 튀어나온다');
  check(await until(() => { const m = window.game.entities.find(e => e.id === 'discord_mask'); return m && m.visible; }, 5000), '디스코드 가면이 벗겨진다');
  await page.waitForTimeout(800); await cap('04_fallen');
  s = await advanceTo('아시발'); check(!!s && s.bgm === 'choimis', `최미스: 아시발. + 브금 choimis (${s?.bgm})`);
  s = await advanceTo('덥다'); await next();
  check(await until(() => window.game.camera.locked === false || window.game.camera.target === window.game.player, 4000), '카메라 잠깐 주인공에게');
  s = await advanceTo('최땡땡'); check(!!s, '내이름은 최땡땡'); await cap('05_name');
  s = await advanceTo('고닉'); check(!!s, '가재맨방 최고 고닉(윙크)'); await page.waitForTimeout(400); await cap('06_wink');
  s = await advanceTo('바로 이'); await next();
  check(await until(() => window.game.zoom.s > 1.8, 4000), '가면 클로즈업'); await page.waitForTimeout(600); await cap('07_mask_closeup');
  s = await advanceTo('감각적'); check(!!s, '하긴 멘트치는건 … (춤)'); await cap('08_sway');
  s = await advanceTo('큼큼'); await next();
  check(await until(() => !window.game.sound.bgmName, 4000), '브금 꺼짐');
  s = await advanceTo('쵸쇼우야'); check(!!s, '내 추구미는... 쵸쇼우야.....');
  check(await until(() => window.game.zoom.s > 1.1, 3000), '천천히 최미스에게 클로즈업(줄과 함께 시작)');
  s = await advanceTo('스읍 미스'); check(await until(() => window.game.entities.find(e => e.id === 'choimis')?.motion?.src?.includes('seup'), 3000), '스읍 미스 동작'); await page.waitForTimeout(600); await cap('09_seup');
  s = await advanceTo('막이래'); check(!!s, '막이래 어헣헣헣');
  // ── 2부 ──
  s = await advanceTo('땡떙씨~?'); check(!!s && s.speaker === '???', '???: 땡떙씨~?'); await next();
  check(await until(() => { const m = window.game.entities.find(e => e.id === 'discord_mask'); return m && m.visible === false; }, 6000), '가면을 위로 던져서 쓴다');
  check(await until(() => window.game.sound.bgmName === 'gasuni', 6000), '브금 gasuni 로 바뀜');
  check(await until(() => ['gasuni1', 'gasuni2', 'gasuni3'].every(id => { const e = window.game.entities.find(x => x.id === id); return e && e.visible; }), 6000), '가순이 셋이 내려온다');
  s = await advanceTo('땡땡오빠'); check(!!s && s.speaker === '가순이1', '가순이1: 꺅 땡땡오빠 여깄었군요');
  const girls = await Promise.all(['gasuni1', 'gasuni2', 'gasuni3'].map(ent)), choi = await ent('choimis');
  check(girls.every(g => g && g.x < choi.x) && new Set(girls.map(g => g.y)).size === 3, `가순이들은 최미스 왼쪽에 어긋나게 ${JSON.stringify(girls.map(g => [g.x, g.y]))}`);
  await cap('10_girls');
  s = await advanceTo('패션'); check(!!s && s.speaker === '가순이3', '가순이3: 패션 대박대박(동동)');
  s = await advanceTo('후훗'); const girlX = (await ent('gasuni1')).x; await next();
  await page.evaluate(x => { window.__girlX = x; }, girlX);
  check(await until(() => { const e = window.game.entities.find(x => x.id === 'gasuni1'); return e && e.x >= window.__girlX + 16; }, 6000), '가순이들 오른쪽(최미스 쪽)으로 이동');
  s = await advanceTo('쵸소우야.'); check(!!s, '내 추구미는 쵸소우야.'); await cap('11_girls_line');
  s = await advanceTo('꺄아아악'); check(!!s && s.speaker === '가순이123', '가순이123: 꺄아아악 …');
  s = await advanceTo('칼로'); check(!!s && s.cam[0] < 250, `카메라 나무 뒤(억빠맨) ${s?.cam}`); await cap('12_tree_cam');
  s = await advanceTo('이따 봐요'); check(!!s && s.cam[0] > 300, `다시 가운데(최미스) ${s?.cam}`);
  s = await advanceTo('네 땡떙씨'); await next();
  check(await until(() => ['gasuni1', 'gasuni2', 'gasuni3'].every(id => { const e = window.game.entities.find(x => x.id === id); return !e || e.dead; }), 8000), '가순이 셋 달려서 올라감');
  s = await advanceTo('후후..'); await next();
  check(await until(() => !window.game.sound.bgmName, 4000), '브금 꺼짐(2)');
  check(await until(() => window.game.entities.find(e => e.id === 'choimis')?.motion?.src?.includes('facepalm'), 4000), '얼굴에 손'); await cap('13_facepalm');
  check(await until(() => { const m = window.game.entities.find(e => e.id === 'discord_mask'); return m && m.visible; }, 6000), '가면을 땅으로 던짐');
  s = await advanceTo('다행이다'); check(!!s, '휴우우우 … 다행이다');
  s = await advanceTo('상관없어'); check(!!s, '나는 상관없어!!!!');
  check(await until(() => window.game.player.y > window.game.entities.find(e => e.id === 'choimis').y + 100, 3000), '일행이 최미스 아래에 순간이동');
  await page.waitForTimeout(2500); await cap('14_pan_down');
  s = await advanceTo('* 어.'); check(!!s && s.cam[1] > 380, `카메라가 내려와 일행·최미스를 같이 잡는다 ${s?.cam}`); await cap('15_eo');
  s = await advanceTo('어 하이'); check(!!s, '... 어 하이');
  s = await advanceTo('스읍 미스'); check(!!s && s.speaker === '억빠맨', '억빠맨: 스읍 미스');
  s = await advanceTo('아 씨발'); check(!!s, '최미스: 아 씨발(점프·진동)');
  s = await advanceTo('뒤진다'); await next();
  check(await until(() => { const c = window.game.entities.find(e => e.id === 'choimis'); const m = window.game.entities.find(e => e.id === 'discord_mask'); return (!c || c.dead) && m && !m.visible; }, 8000), '가면 챙겨서 위로 도망');
  await cap('16_escape');
  s = await advanceTo('돈달라고'); check(!!s && s.speaker === '억빠맨', '왜 돈달라고 안해요?');
  s = await advanceTo('쫒아가'); check(!!s && s.speaker === '경섭', '아 맞네 씨발 야 쫒아가.'); await next();
  check(await until(() => !window.game.dialogue.running && window.game.flags.glade_done, 8000), '연출 끝 → glade_done');
  await page.waitForTimeout(400); await cap('17_end');
} catch (e) { fails += 1; console.log('FAIL exception', e.message); await cap('99_error'); }
check(errors.length === 0, `페이지 오류 없음 ${errors.slice(0, 3).join(' | ')}`);
await browser.close();
console.log('fails=' + fails);
process.exit(fails ? 1 : 0);
