// 벚꽃 숲 2·3(BUILD264): QA jjajang_sakura2_bridge(갈림목)에서 오른쪽 샛길 끝 → 카메라가 오른쪽(다리)으로 → 대사 넷 → 카메라 복귀 → 억빠맨 → 위로 → 벚꽃 숲 3 → 위·오른쪽 → 뗏목 C → 4초 꽃잎 → 아래 뭍 도착. 실행: tests/playtest/run.sh jjajang-sakura2
import fs from 'node:fs'; import path from 'node:path';
import { chromium } from 'playwright-core';
const shots = process.env.SHOT_DIR; fs.mkdirSync(shots, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXE, headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'warning' && /cutscene|엔티티 없음|동작 없음|없음/.test(m.text())) errors.push('warn: ' + m.text()); });
let fails = 0;
const check = (ok, msg) => { if (!ok) { fails += 1; console.log('FAIL', msg); } else console.log('ok', msg); };
const cap = async n => { await page.screenshot({ path: path.join(shots, 'sakura2_' + n + '.png') }); };
const press = async key => { await page.keyboard.down(key); await page.waitForTimeout(60); await page.keyboard.up(key); };
const until = (fn, ms) => page.waitForFunction(fn, null, { timeout: ms, polling: 30 }).then(() => true).catch(() => false);
const ev = fn => page.evaluate(fn);
const go = async (key, cond, ms) => { await page.evaluate(c => { window.__cond = c; }, cond); await page.keyboard.down(key); const ok = await until(() => new Function('g', 'return ' + window.__cond)(window.game), ms); await page.keyboard.up(key); return ok; };
const st = () => ev(() => { const g = window.game; return { map: g.mapId, text: g.textbox.node?.text || null, speaker: g.textbox.node?.speaker || null, state: g.textbox.state, cam: [Math.round(g.camera.x), Math.round(g.camera.y)], bgm: g.sound.bgmName, px: Math.round(g.player.x), py: Math.round(g.player.y), petals: g.petals?.count ?? -1, ride: !!g.ride, rideTime: +(g.ride?.rideTime ?? -1).toFixed(2) }; });
const next = async () => { await until(() => window.game.textbox.state === 'waiting', 8000); await press('KeyC'); };
const advanceTo = async (needle, ms = 40000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { const s = await st(); if (s.text && s.text.includes(needle)) return s; if (s.text) await next(); await page.waitForTimeout(100); } return null; };
try {
  await page.goto('http://localhost:8000/?qa=jjajang_sakura2_bridge');
  check(await until(() => window.game?.mapId === 'jjajang_sakura2' && !window.game.transitioning, 30000), '벚꽃 숲 2 갈림목 QA');
  await page.waitForTimeout(800); let s = await st(); check(s.bgm === 'sakura' && s.petals > 0, `브금 sakura 유지·꽃잎 ${s.petals}`); await cap('00_junction');
  check(await go('ArrowUp', 'g.player.y <= 9 * 32 + 8', 8000), '갈림목 높이까지');
  const camBefore = (await st()).cam;
  check(await go('ArrowRight', 'g.dialogue.running', 12000), '오른쪽 샛길 끝 → 연출 시작');
  check(await until(() => window.game.camera.x > 30 * 32 - 240, 4000), '카메라가 오른쪽(벚꽃다리)으로 간다'); await page.waitForTimeout(400); await cap('01_bridge');
  s = await st(); check(s.bgm === 'sakura', '브금 유지');
  const onBridge = await ev(() => { const g = window.game; const b = g.entities.find(e => e.id === 'sakura_bridge'); const c = g.entities.find(e => e.id === 'choimis'); const girls = ['gasuni1', 'gasuni2', 'gasuni3'].map(id => g.entities.find(e => e.id === id)); return { bridge: !!b?.image, choimis: !!c && c.visible !== false && !!c.motion, girls: girls.every(x => x && x.visible !== false), camX: Math.round(g.camera.x), choimisX: Math.round(c?.x ?? -1) }; });
  check(onBridge.bridge && onBridge.choimis && onBridge.girls && onBridge.choimisX > onBridge.camX && onBridge.choimisX < onBridge.camX + 480, `다리·가면 쓴 최미스·가순이 셋이 화면 안 ${JSON.stringify(onBridge)}`);
  s = await advanceTo('허허 스읍'); check(!!s && s.speaker === '최미스', '최미스: 허허 스읍 미스 ㅋㅋㅋㅋ');
  s = await advanceTo('미용실'); check(!!s && s.speaker === '가순이1', '가순이1: 떙땡이오빠 미용실 어디다녀요?');
  s = await advanceTo('인스타'); check(!!s && s.speaker === '최미스', '최미스: 아 ㅋㅋ 전 뭐 인스타에서 …');
  s = await advanceTo('스읍 ㅋㅋㅋㅋㅋ'); check(!!s, '최미스: 스읍 ㅋㅋㅋㅋㅋ'); await next();
  check(await until(() => window.game.camera.x < 20 * 32, 5000), '카메라가 다시 주인공 쪽으로'); await cap('02_back');
  s = await advanceTo('좆같네'); check(!!s && s.speaker === '억빠맨' && Math.abs(s.cam[0] + 240 - (s.px + 12)) < 48, `억빠맨: 좆같네씨발 (카메라가 주인공에게 돌아옴 ${s?.cam}, 주인공 ${s?.px}; 처음 ${camBefore})`); await next();
  check(await until(() => !window.game.dialogue.running && window.game.flags.sakura2_bridge_done, 6000), '연출 끝');
  // 위로 → 벚꽃 숲 3
  check(await go('ArrowLeft', 'g.player.x <= 11 * 32', 12000), '갈림목으로');
  check(await go('ArrowUp', "g.mapId === 'jjajang_sakura3'", 20000), '윗줄 문 → 벚꽃 숲 3');
  await page.waitForFunction(() => !window.game.transitioning, null, { timeout: 10000 }); await page.waitForTimeout(500);
  s = await st(); check(s.bgm === 'sakura' && s.petals > 0, `3: 브금 유지·꽃잎 ${s.petals}`); await cap('03_map3');
  const S3 = await ev(() => window.game.map.def.meta.sakura3);
  check(await go('ArrowUp', `g.player.y <= ${(S3.roadRows[0] + 1) * 32 + 8}`, 20000), '위로');
  check(await go('ArrowRight', `g.player.x >= ${(S3.shoreCol + 1) * 32 - 30}`, 20000), '오른쪽으로 물가 끝까지'); await cap('04_dock');
  const petalsBefore = (await st()).petals;
  await press('KeyC'); check(await until(() => window.game.ride && window.game.ride.moving, 8000), '뗏목 C → 걸어 올라타고 출발');
  check(await until(() => (window.game.ride?.rideTime || 0) >= 4.05, 8000), '4초');
  await page.waitForTimeout(150); s = await st(); await cap('05_gust');
  check(s.petals > petalsBefore + 80, `4초쯤 꽃잎 휘날림(${petalsBefore} → ${s.petals})`);
  const t4 = await ev(() => ({ x: Math.round(window.game.ride.x), y: Math.round(window.game.ride.y) }));
  check(await until(() => !window.game.ride, 12000), '뗏목 도착(아래 뭍)');
  s = await st(); await cap('06_landing');
  const landed = await ev(() => { const g = window.game; const r = g.entities.find(e => e.id === 'sakura_raft'); return { rideTime: +r.rideTime.toFixed(1), px: Math.round(g.player.x), py: Math.round(g.player.y), raftY: Math.round(r.y), party: [...g.party], followers: g.entities.filter(e => e.def?.type === 'follower' && e.visible !== false).length }; });
  check(landed.rideTime >= 7.5 && landed.rideTime <= 9.5, `뗏목 8초쯤 (${landed.rideTime}초)`);
  check(landed.py > landed.raftY + 20 && landed.px > t4.x && landed.followers === 2, `오른쪽으로 갔다가 아래 뭍에 내렸고 동료 둘 복귀 ${JSON.stringify(landed)}`);
  // 반대로도 탄다(사용자 2026-09-20 “뗏목 반대로는 안타지네”): 뭍에서 뗏목 쪽(위)을 보고 C → 되돌아가 물가에 내린다
  await press('ArrowUp'); await page.waitForTimeout(200);
  check(await ev(() => window.game.player.facing === 'up' && !window.game.ride), '뗏목 쪽(위)을 본다');
  await press('KeyC'); check(await until(() => window.game.ride && window.game.ride.moving, 8000), '뭍에서 C → 반대로 탄다');
  check(await until(() => !window.game.ride, 14000), '되돌아가 물가에 내린다');
  const back = await ev(() => { const g = window.game; const r = g.entities.find(e => e.id === 'sakura_raft'); return { px: Math.round(g.player.x), raftX: Math.round(r.x), raftY: Math.round(r.y), followers: g.entities.filter(e => e.def?.type === 'follower' && e.visible !== false).length }; });
  check(back.raftX < 600 && back.px < back.raftX && back.followers === 2, `뗏목이 물가로 돌아오고 주인공은 뭍(왼쪽) ${JSON.stringify(back)}`); await cap('07_return');
} catch (e) { fails += 1; console.log('FAIL exception', e.message); await cap('99_error'); }
check(errors.length === 0, `페이지 오류 없음 ${errors.slice(0, 3).join(' | ')}`);
await browser.close();
console.log('fails=' + fails);
process.exit(fails ? 1 : 0);
